# Generated by Django 5.2.4 on 2025-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loanrequestform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequestform',
            name='aadhaar_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhaar_back/'),
        ),
        migrations.AddField(
            model_name='loanrequestform',
            name='aadhaar_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhaar_front/'),
        ),
        migrations.AddField(
            model_name='loanrequestform',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='loanrequestform',
            name='kyc_status',
            field=models.CharField(choices=[('Not Uploaded', 'Not Uploaded'), ('Under Review', 'Under Review'), ('verified', 'verified')], default='Not Uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='loanrequestform',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/pan_card/'),
        ),
        migrations.AddField(
            model_name='loanrequestform',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequestform',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfie/'),
        ),
    ]
