# Generated by Django 5.2.4 on 2025-11-03 15:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanrequestform_aadhaar_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequestform',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='loanrequestform',
            name='starts_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='EmiSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_componets', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_componets', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emis', to='loans.loanrequestform')),
            ],
            options={
                'ordering': ['month_number'],
            },
        ),
    ]
