# Generated by Django 5.2.4 on 2025-11-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanrequestform_interest_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emischedule',
            old_name='interest_componets',
            new_name='interest_componet',
        ),
        migrations.RenameField(
            model_name='emischedule',
            old_name='principal_componets',
            new_name='principal_componet',
        ),
    ]
