# Generated by Django 5.2.4 on 2025-11-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_rename_interest_componets_emischedule_interest_componet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emischedule',
            old_name='interest_componet',
            new_name='interest_component',
        ),
        migrations.RenameField(
            model_name='emischedule',
            old_name='principal_componet',
            new_name='principal_component',
        ),
    ]
