# Generated by Django 5.2.4 on 2026-04-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_rename_interest_componet_emischedule_interest_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequestform',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_UPLOAD', 'Not Uploaded'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'verified')], default='NOT_UPLOAD', max_length=20),
        ),
    ]
