# Generated by Django 5.2.4 on 2026-06-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loanrequestform_kyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequestform',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_UPLOAD', 'Not Uploaded'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'verified'), ('REJECTED', 'rejected')], default='NOT_UPLOAD', max_length=20),
        ),
    ]
