# Generated by Django 5.2.4 on 2026-01-05 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0006_rename_interest_componet_emischedule_interest_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('created', 'created'), ('success', 'success'), ('failed', 'failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('emi', models.ForeignKey(default='payments', on_delete=django.db.models.deletion.CASCADE, to='loans.emischedule')),
                ('loan', models.ForeignKey(default='payments', on_delete=django.db.models.deletion.CASCADE, to='loans.loanrequestform')),
            ],
        ),
    ]
